@ECHO OFF
tools\xml2html members.xml templates\TeamMember.xsl docs\AndreaRiddle.html "/Team/Member[1]"
tools\xml2html members.xml templates\TeamMember.xsl docs\AndreaRiddle-en.html "/Team/Member[1]" "en"
tools\xml2html members.xml templates\TeamMember.xsl docs\MartineDrapeau.html "/Team/Member[2]"
tools\xml2html members.xml templates\TeamMember.xsl docs\SylvieLarouche.html "/Team/Member[3]"
tools\xml2html members.xml templates\TeamMember.xsl docs\SylvieLemire.html "/Team/Member[4]"
tools\xml2html members.xml templates\TeamMember.xsl docs\JeanFrancoisFecteau.html "/Team/Member[5]"
tools\xml2html members.xml templates\TeamMember.xsl docs\MarieEveRobillard.html "/Team/Member[6]"
tools\xml2html members.xml templates\TeamMember.xsl docs\IsabelleVerret.html "/Team/Member[7]"
tools\xml2html members.xml templates\TeamMember.xsl docs\MurielleGuillotte.html "/Team/Member[8]"
tools\xml2html members.xml templates\TeamMember.xsl docs\JacquesMcNulty.html "/Team/Member[9]"
tools\xml2html members.xml templates\TeamMember.xsl docs\JacquesMcNulty-en.html "/Team/Member[9]" "en"
tools\xml2html members.xml templates\TeamMember.xsl docs\MarieJoseeLeger.html "/Team/Member[10]"
tools\xml2html members.xml templates\TeamMember.xsl docs\AmiPuig.html "/Team/Member[11]"
tools\xml2html members.xml templates\TeamMember.xsl docs\ChristineLettre.html "/Team/Member[12]"
tools\xml2html members.xml templates\TeamMember.xsl docs\AlexandraColle.html "/Team/Member[13]"
tools\xml2html members.xml templates\TeamMember.xsl docs\MariseGagne.html "/Team/Member[14]"
tools\xml2html members.xml templates\TeamMember.xsl docs\FranciscaGagne.html "/Team/Member[15]"
tools\xml2html members.xml templates\TeamMember.xsl docs\EmmanuelleBourgault.html "/Team/Member[16]"
tools\xml2html members.xml templates\TeamMember.xsl docs\LindaParent.html "/Team/Member[17]"
tools\xml2html members.xml templates\TeamMembers2Col.xsl docs\team.html "/Team"
