@ECHO OFF
tools\xml2html members.xml templates\TeamMember.xsl site\AndreaRiddle.html "/Team/Member[1]"
tools\xml2html members.xml templates\TeamMember.xsl site\AndreaRiddle-en.html "/Team/Member[1]" "en"
tools\xml2html members.xml templates\TeamMember.xsl site\MartineDrapeau.html "/Team/Member[2]"
tools\xml2html members.xml templates\TeamMember.xsl site\NathalieProulx.html "/Team/Member[3]"
tools\xml2html members.xml templates\TeamMember.xsl site\SylvieLarouche.html "/Team/Member[4]"
tools\xml2html members.xml templates\TeamMember.xsl site\AnnieJacques.html "/Team/Member[5]"
tools\xml2html members.xml templates\TeamMember.xsl site\SylvieLemire.html "/Team/Member[6]"
tools\xml2html members.xml templates\TeamMember.xsl site\NathalieDrolet.html "/Team/Member[7]"
tools\xml2html members.xml templates\TeamMember.xsl site\LindaParent.html "/Team/Member[8]"
tools\xml2html members.xml templates\TeamMember.xsl site\MarieJoseeLeger.html "/Team/Member[9]"
tools\xml2html members.xml templates\TeamMember.xsl site\IsabelleVerret.html "/Team/Member[10]"
tools\xml2html members.xml templates\TeamMember.xsl site\MurielleGuillotte.html "/Team/Member[11]"
tools\xml2html members.xml templates\TeamMember.xsl site\JacquesMcNulty.html "/Team/Member[12]"
tools\xml2html members.xml templates\TeamMember.xsl site\JacquesMcNulty-en.html "/Team/Member[12]" "en"
tools\xml2html members.xml templates\TeamMember.xsl site\NicoleDesjardins.html "/Team/Member[13]"
tools\xml2html members.xml templates\TeamMember.xsl site\LuceMontpetit.html "/Team/Member[14]"
tools\xml2html members.xml templates\TeamMember.xsl site\AnniePaquin.html "/Team/Member[15]"
tools\xml2html members.xml templates\TeamMember.xsl site\AnnieEveGagnonMakrous.html "/Team/Member[16]"
tools\xml2html members.xml templates\TeamMember.xsl site\MarieEveRobillard.html "/Team/Member[17]"
tools\xml2html members.xml templates\TeamMember.xsl site\CassandreBelangerLegault.html "/Team/Member[18]"
tools\xml2html members.xml templates\TeamMember.xsl site\AmiPuig.html "/Team/Member[19]"
tools\xml2html members.xml templates\TeamMember.xsl site\NatanPlouffe.html "/Team/Member[20]"
tools\xml2html members.xml templates\TeamMember.xsl site\FrederiqueLandryLepine.html "/Team/Member[21]"
tools\xml2html members.xml templates\TeamMember.xsl site\ReneBarrette.html "/Team/Member[22]"
tools\xml2html members.xml templates\TeamMembers2Col.xsl site\team.html "/Team"
