@ECHO OFF
xml\xml2html xml\TeamMembers.xml xml\TeamMember.xsl Site\AndreaRiddle.html "/Team/Member[1]"
xml\xml2html xml\TeamMembers.xml xml\TeamMember.xsl Site\AndreaRiddle-en.html "/Team/Member[1]" "en"
xml\xml2html xml\TeamMembers.xml xml\TeamMember.xsl Site\MartineDrapeau.html "/Team/Member[2]"
xml\xml2html xml\TeamMembers.xml xml\TeamMember.xsl Site\NathalieProulx.html "/Team/Member[3]"
xml\xml2html xml\TeamMembers.xml xml\TeamMember.xsl Site\SylvieLarouche.html "/Team/Member[4]"
xml\xml2html xml\TeamMembers.xml xml\TeamMember.xsl Site\AnnieJacques.html "/Team/Member[5]"
xml\xml2html xml\TeamMembers.xml xml\TeamMember.xsl Site\SylvieLemire.html "/Team/Member[6]"
xml\xml2html xml\TeamMembers.xml xml\TeamMember.xsl Site\NathalieDrolet.html "/Team/Member[7]"
xml\xml2html xml\TeamMembers.xml xml\TeamMember.xsl Site\LindaParent.html "/Team/Member[8]"
xml\xml2html xml\TeamMembers.xml xml\TeamMember.xsl Site\MarieJoseeLeger.html "/Team/Member[9]"
xml\xml2html xml\TeamMembers.xml xml\TeamMember.xsl Site\JeanFrancoisFecteau.html "/Team/Member[10]"
xml\xml2html xml\TeamMembers.xml xml\TeamMember.xsl Site\IsabelleVerret.html "/Team/Member[11]"
xml\xml2html xml\TeamMembers.xml xml\TeamMember.xsl Site\MurielleGuillotte.html "/Team/Member[12]"
xml\xml2html xml\TeamMembers.xml xml\TeamMember.xsl Site\JacquesMcNulty.html "/Team/Member[13]"
xml\xml2html xml\TeamMembers.xml xml\TeamMember.xsl Site\JacquesMcNulty-en.html "/Team/Member[13]" "en"
xml\xml2html xml\TeamMembers.xml xml\TeamMember.xsl Site\NicoleDesjardins.html "/Team/Member[14]"
xml\xml2html xml\TeamMembers.xml xml\TeamMember.xsl Site\LuceMontpetit.html "/Team/Member[15]"
xml\xml2html xml\TeamMembers.xml xml\TeamMember.xsl Site\AnniePaquin.html "/Team/Member[16]"
xml\xml2html xml\TeamMembers.xml xml\TeamMember.xsl Site\AnnieEveGagnonMakrous.html "/Team/Member[17]"
xml\xml2html xml\TeamMembers.xml xml\TeamMember.xsl Site\MarieEveRobillard.html "/Team/Member[18]"
xml\xml2html xml\TeamMembers.xml xml\TeamMember.xsl Site\CassandreBelangerLegault.html "/Team/Member[19]"
xml\xml2html xml\TeamMembers.xml xml\TeamMember.xsl Site\ReneBarrette.html "/Team/Member[20]"
xml\xml2html xml\TeamMembers.xml xml\TeamMember.xsl Site\MariePhilippeBourget.html "/Team/Member[21]"
xml\xml2html xml\TeamMembers.xml xml\TeamMembers2Col.xsl Site\team.html "/Team"
